use_frameworks!

platform :ios, '13.0'

target 'BSWHPhotoPicker_Example' do
  pod 'BSWHPhotoPicker', :path => '../'
  pod 'SnapKit'
  pod 'Localize-Swift', '~> 3.2.0'
  pod 'SwiftGen', '~> 6.6.3', :configurations => ['Debug']

  target 'BSWHPhotoPicker_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
